### ISSUE TITLE
Cache is too slow

### ISSUE THREAD

**Issue by bgilbert** [cmusatyalab/opendiamond#26]
Even when a search has a very high drop rate and is running completely from cache, 8 servers can only process ~6000 objects per second.  For each object, we have to compute result cache keys, do a Redis MGET, parse the resulting JSON, find a dropping filter, and resolve its dependencies.  This is largely CPU-bound in diamondd, so the FilterStackRunners end up contending for the GIL.

**Comment by fzqneo** [comment]
We changed multithreading to multiprocessing in v9.0.0
The new potential bottlenecks are: (1) Redis itself; (2) parsing ScopeList.
In a few simple all-drop-cached tests, (2) appears to be the bottleneck at about 9000/s on a single machine. It seems to be the limit of the Python xml module.
