### ISSUE TITLE
out-of-date date

### ISSUE THREAD

**Issue by spressomonkey** [cmusatyalab/opendiamond#43]
When attempting to build OpenDiamond on OS X (Yosemite/HomeBrew, I encountered an error in RFC where it complains about an "out-of-date" date. This prevents any further building of the project.

Here's the stack trace below:

WARNING: Incomplete and out-of date <date/> element: <date year="2012"/>
Traceback (most recent call last):
  File "/usr/local/bin/xml2rfc", line 254, in <module>
    main()
  File "/usr/local/bin/xml2rfc", line 219, in main
    htmlwriter.write(filename)
  File "/usr/local/lib/python2.7/site-packages/xml2rfc/writers/base.py", line 1207, in write
    self._format_date()
  File "/usr/local/lib/python2.7/site-packages/xml2rfc/writers/base.py", line 488, in _format_date
    datetime.datetime.strptime(date.attrib.get('year')+date.attrib.get('month'), '%Y%B')
TypeError: cannot concatenate 'str' and 'NoneType' objects
make[2]: *** [doc/diamond-protocol.html] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by bgilbert** [comment]
Thanks for the report and patch.  It looks like the additional check was added in xml2rfc 2.4.2.  I've updated the `<date>` element with the full modification date of the document.

FYI, OpenDiamond has not been tested on Mac OS X.  It may work, but there may well be some Linux-specific assumptions in the code.
